### ISSUE TITLE
Should we create project specific folders?

### ISSUE THREAD

**Issue by NelleV** [machine-shop/updates#1]
I expect this folder is going to be filled in and quite messy in a short period of time :)

**Comment by stefanv** [comment]
That sounds like a good idea.  Let's remember to mention that at our inaugural project meetings.

**Comment by NelleV** [comment]
I'll do it, but just to make sure I don't miss any.
- [ ] admin (for us)
- [ ] scikit-image
- [ ] matplotlib
- [ ] cesium
- [ ] fmri_music

**Comment by stefanv** [comment]
Let's use main or project or coordination or admin instead of
management.  The rest looks great.

**Comment by NelleV** [comment]
sounds good.
